In [48]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
import warnings
warnings.filterwarnings('ignore')

In [49]:
dataset = pd.read_csv('forestfires.csv')
dataset[:5]

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,...,0,0,0,0,1,0,0,0,0,small
1,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,...,0,0,0,0,0,0,0,1,0,small
2,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,...,0,0,0,0,0,0,0,1,0,small
3,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,...,0,0,0,0,1,0,0,0,0,small
4,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,...,0,0,0,0,1,0,0,0,0,small

In [50]:
dataset.drop(["month","day"],axis=1,inplace = True)

In [51]:
dataset["size_category"].value_counts()

small    378
large    139
Name: size_category, dtype: int64

In [52]:
dataset.isnull().sum()

FFMC             0
DMC              0
DC               0
ISI              0
temp             0
RH               0
wind             0
rain             0
area             0
dayfri           0
daymon           0
daysat           0
daysun           0
daythu           0
daytue           0
daywed           0
monthapr         0
monthaug         0
monthdec         0
monthfeb         0
monthjan         0
monthjul         0
monthjun         0
monthmar         0
monthmay         0
monthnov         0
monthoct         0
monthsep         0
size_category    0
dtype: int64

In [53]:
dataset.describe()

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,...,monthdec,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep
count,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,...,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000
mean,90.644681,110.872340,547.940039,9.021663,18.889168,44.288201,4.017602,0.021663,12.847292,0.164410,...,0.017408,0.038685,0.003868,0.061896,0.032882,0.104449,0.003868,0.001934,0.029014,0.332689
std,5.520111,64.046482,248.066192,4.559477,5.806625,16.317469,1.791653,0.295959,63.655818,0.371006,...,0.130913,0.193029,0.062137,0.241199,0.178500,0.306138,0.062137,0.043980,0.168007,0.471632
min,18.700000,1.100000,7.900000,0.000000,2.200000,15.000000,0.400000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,90.200000,68.600000,437.700000,6.500000,15.500000,33.000000,2.700000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,91.600000,108.300000,664.200000,8.400000,19.300000,42.000000,4.000000,0.000000,0.520000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,92.900000,142.400000,713.900000,10.800000,22.800000,53.000000,4.900000,0.000000,6.570000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,96.200000,291.300000,860.600000,56.100000,33.300000,100.000000,9.400000,6.400000,1090.840000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [54]:
dataset.corr()

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,...,monthdec,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep
FFMC,1.000000,0.382619,0.330512,0.531805,0.431532,-0.300995,-0.028485,0.056702,0.040122,0.019306,...,-0.137044,-0.281535,-0.454771,0.031833,-0.040634,-0.074327,-0.037230,-0.088964,-0.005998,0.076609
DMC,0.382619,1.000000,0.682192,0.305128,0.469594,0.073795,-0.105342,0.074790,0.072994,-0.012010,...,-0.176301,-0.317899,-0.105647,-0.001946,-0.050403,-0.407404,-0.081980,-0.074218,-0.187632,0.110907
DC,0.330512,0.682192,1.000000,0.229154,0.496208,-0.039192,-0.203466,0.035861,0.049383,-0.004220,...,-0.105642,-0.399277,-0.115064,-0.100887,-0.186183,-0.650427,-0.114209,-0.078380,0.093279,0.531857
ISI,0.531805,0.305128,0.229154,1.000000,0.394287,-0.132517,0.106826,0.067668,0.008258,0.046695,...,-0.162322,-0.249777,-0.103588,0.020982,0.111516,-0.143520,-0.060493,-0.076559,-0.071154,-0.068877
temp,0.431532,0.469594,0.496208,0.394287,1.000000,-0.527390,-0.227116,0.069491,0.097844,-0.071949,...,-0.329648,-0.320015,-0.146520,0.142588,0.051015,-0.341797,-0.045540,-0.053798,-0.053513,0.088006
RH,-0.300995,0.073795,-0.039192,-0.132517,-0.527390,1.000000,0.069410,0.099751,-0.075519,0.064506,...,-0.047714,0.140430,0.170923,0.013185,0.009382,-0.089836,0.086822,-0.035885,-0.072334,-0.062596
wind,-0.028485,-0.105342,-0.203466,0.106826,-0.227116,0.069410,1.000000,0.061119,0.012317,0.118090,...,0.269702,-0.029431,-0.070245,-0.040645,0.012124,0.181433,0.015054,0.011864,-0.053850,-0.181476
rain,0.056702,0.074790,0.035861,0.067668,0.069491,0.099751,0.061119,1.000000,-0.007366,-0.004261,...,-0.009752,-0.014698,-0.004566,-0.013390,-0.013510,-0.020744,-0.004566,-0.003225,-0.012665,-0.051733
area,0.040122,0.072994,0.049383,0.008258,0.097844,-0.075519,0.012317,-0.007366,1.000000,-0.052911,...,0.001010,-0.020732,-0.012589,0.006149,-0.020314,-0.045596,0.006264,-0.008893,-0.016878,0.056573
dayfri,0.019306,-0.012010,-0.004220,0.046695,-0.071949,0.064506,0.118090,-0.004261,-0.052911,1.000000,...,-0.019140,0.046323,-0.027643,-0.048969,0.006000,0.036205,0.056423,-0.019527,-0.045585,0.107671
daymon,-0.059396,-0.107921,-0.052993,-0.158601,-0.136529,0.009376,-0.063881,-0.029945,-0.021206,-0.181293,...,0.114519,0.003933,-0.025470,-0.013300,0.017553,0.077125,-0.025470,-0.017992,0.060975,0.039632
daysat,-0.019637,-0.003653,-0.035189,-0.038585,0.034899,-0.023869,-0.063799,-0.032271,0.087868,-0.195372,...,-0.058625,0.020406,0.057019,0.060945,-0.022408,0.021024,0.057019,-0.019390,0.017584,-0.032783
daysun,-0.089517,0.025355,-0.001431,-0.003243,0.014403,0.136220,0.027981,-0.017872,-0.020463,-0.210462,...,-0.024966,0.008416,0.050887,-0.018241,0.024540,-0.047726,-0.029568,-0.020887,0.007252,-0.048817
daythu,0.071730,0.087672,0.051859,-0.022406,0.051432,-0.123061,-0.062553,-0.026798,0.020121,-0.162237,...,-0.002838,-0.042278,-0.022793,-0.019300,-0.000195,-0.026885,-0.022793,-0.016101,-0.063223,0.008984
daytue,0.011225,0.000016,0.028368,0.068610,0.035630,-0.014211,0.053396,0.139311,-0.001333,-0.166728,...,-0.005125,-0.014491,-0.023424,0.049688,-0.069308,-0.032351,-0.023424,0.117121,0.005008,-0.028570
daywed,0.093908,0.017939,0.024803,0.125415,0.090580,-0.087508,-0.019965,-0.020744,-0.011452,-0.151487,...,0.002899,-0.035713,-0.021282,-0.008985,0.043422,-0.033917,-0.021282,-0.015034,0.016325,-0.053222
monthapr,-0.117199,-0.197543,-0.268211,-0.106478,-0.157051,0.021235,0.048266,-0.009752,-0.008280,-0.019140,...,-0.017717,-0.026701,-0.008295,-0.034190,-0.024543,-0.045456,-0.008295,-0.005860,-0.023008,-0.093982
monthaug,0.228103,0.497928,0.279361,0.334639,0.351404,0.054761,0.028577,0.093101,-0.004187,-0.100837,...,-0.098941,-0.149116,-0.046323,-0.190937,-0.137065,-0.253859,-0.046323,-0.032724,-0.128493,-0.524858
monthdec,-0.137044,-0.176301,-0.105642,-0.162322,-0.329648,-0.047714,0.269702,-0.009752,0.001010,-0.019140,...,1.000000,-0.026701,-0.008295,-0.034190,-0.024543,-0.045456,-0.008295,-0.005860,-0.023008,-0.093982
monthfeb,-0.281535,-0.317899,-0.399277,-0.249777,-0.320015,0.140430,-0.029431,-0.014698,-0.020732,0.046323,...,-0.026701,1.000000,-0.012501,-0.051528,-0.036989,-0.068508,-0.012501,-0.008831,-0.034676,-0.141642
monthjan,-0.454771,-0.105647,-0.115064,-0.103588,-0.146520,0.170923,-0.070245,-0.004566,-0.012589,-0.027643,...,-0.008295,-0.012501,1.000000,-0.016007,-0.011491,-0.021282,-0.003883,-0.002743,-0.010772,-0.044001
monthjul,0.031833,-0.001946,-0.100887,0.020982,0.142588,0.013185,-0.040645,-0.013390,0.006149,-0.048969,...,-0.034190,-0.051528,-0.016007,1.000000,-0.047363,-0.087722,-0.016007,-0.011308,-0.044402,-0.181367
monthjun,-0.040634,-0.050403,-0.186183,0.111516,0.051015,0.009382,0.012124,-0.013510,-0.020314,0.006000,...,-0.024543,-0.036989,-0.011491,-0.047363,1.000000,-0.062972,-0.011491,-0.008117,-0.031874,-0.130195
monthmar,-0.074327,-0.407404,-0.650427,-0.143520,-0.341797,-0.089836,0.181433,-0.020744,-0.045596,0.036205,...,-0.045456,-0.068508,-0.021282,-0.087722,-0.062972,1.000000,-0.021282,-0.015034,-0.059034,-0.241135
monthmay,-0.037230,-0.081980,-0.114209,-0.060493,-0.045540,0.086822,0.015054,-0.004566,0.006264,0.056423,...,-0.008295,-0.012501,-0.003883,-0.016007,-0.011491,-0.021282,1.000000,-0.002743,-0.010772,-0.044001
monthnov,-0.088964,-0.074218,-0.078380,-0.076559,-0.053798,-0.035885,0.011864,-0.003225,-0.008893,-0.019527,...,-0.005860,-0.008831,-0.002743,-0.011308,-0.008117,-0.015034,-0.002743,1.000000,-0.007610,-0.031083
monthoct,-0.005998,-0.187632,0.093279,-0.071154,-0.053513,-0.072334,-0.053850,-0.012665,-0.016878,-0.045585,...,-0.023008,-0.034676,-0.010772,-0.044402,-0.031874,-0.059034,-0.010772,-0.007610,1.000000,-0.122053
monthsep,0.076609,0.110907,0.531857,-0.068877,0.088006,-0.062596,-0.181476,-0.051733,0.056573,0.107671,...,-0.093982,-0.141642,-0.044001,-0.181367,-0.130195,-0.241135,-0.044001,-0.031083,-0.122053,1.000000

In [55]:
dataset.loc[dataset["size_category"]=='small','size_category']=0

In [56]:
dataset.loc[dataset["size_category"]=='large','size_category']=1

In [57]:
dataset["size_category"].value_counts()

0    378
1    139
Name: size_category, dtype: int64

In [58]:
def norm_func(i):
     x = (i-i.min())	/	(i.max()	-	i.min())
     return (x)

In [59]:
predictors = dataset.iloc[:,0:28]
target = dataset.iloc[:,28]

In [60]:
predictors

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,...,monthdec,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep
0,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.00,1,...,0,0,0,0,0,1,0,0,0,0
1,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.00,0,...,0,0,0,0,0,0,0,0,1,0
2,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.00,0,...,0,0,0,0,0,0,0,0,1,0
3,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.00,1,...,0,0,0,0,0,1,0,0,0,0
4,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.00,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,6.44,0,...,0,0,0,0,0,0,0,0,0,0
513,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,54.29,0,...,0,0,0,0,0,0,0,0,0,0
514,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,11.16,0,...,0,0,0,0,0,0,0,0,0,0
515,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,0.00,0,...,0,0,0,0,0,0,0,0,0,0
516,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,0.00,0,...,0,0,0,0,0,0,0,1,0,0

In [61]:
target

0      0
1      0
2      0
3      0
4      0
      ..
512    1
513    1
514    1
515    0
516    0
Name: size_category, Length: 517, dtype: object

In [62]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(predictors,target, test_size=0.3,stratify = target)

In [63]:
# Encoding categorical data for independent variables 
from sklearn.preprocessing import LabelEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 2] = labelencoder_X_1.fit_transform(X[:, 2]) #For month
labelencoder_X_2 = LabelEncoder()
X[:, 3] = labelencoder_X_2.fit_transform(X[:, 3]) #For weekday

In [64]:
'''
#Convert to Acres then Classify Size
Class 1.A - one acre or less;
Class 2.B - more than one acre, but less than 10 acres;
Class 3.C - 10 acres or more, but less than 100 acres;
Class 4.D - 100 acres or more, but less than 300 acres;
Class 5.E - 300 acres or more, but less than 1,000 acres;
Class 6.F - 1,000 acres or more, but less than 5,000 acres;
'''
y = dataset.iloc[:, 12].values
for i in range(0, len(y)):
    y[i] = (y[i]*2.47)
    if y[i] < 1.0:
        y[i] = 1
    elif y[i] < 10.0:
        y[i] = 2
    elif y[i] < 100.0:
        y[i] = 3
    elif y[i] < 300.0:
        y[i] = 4
    elif y[i] < 1000.0:
        y[i] = 5
    elif y[i] < 5000.0:
        y[i] = 6
    else:
        y[i] = 7

y_Corrected = y.astype(int) 
y_Corrected[:10]

array([1, 1, 1, 1, 2, 2, 1, 1, 1, 1])

In [65]:
def prep_model(hidden_dim):
    model = Sequential()
    for i in range(1,len(hidden_dim)-1):
        if (i==1):
            model.add(Dense(hidden_dim[i],input_dim=hidden_dim[0],activation="relu"))
        else:
            model.add(Dense(hidden_dim[i],activation="relu"))
    model.add(Dense(hidden_dim[-1],kernel_initializer="normal",activation="sigmoid"))
    model.compile(loss="binary_crossentropy",optimizer = "rmsprop",metrics = ["accuracy"])
    return model

In [66]:
first_model = prep_model([28,50,40,20,1])
pred_train = first_model.predict(np.array(x_train))

12/12 [==============================] - 0s 2ms/step

In [67]:
pred_train = pd.Series([i[0] for i in pred_train])

In [68]:
size = ["small","large"]
pred_train_class = pd.Series(["small"]*361)
pred_train_class[[i>0.5 for i in pred_train]]= "large"

In [69]:
train = pd.concat([x_train,y_train],axis=1)
train["size_category"].value_counts()

0    264
1     97
Name: size_category, dtype: int64

In [70]:
from sklearn.metrics import confusion_matrix
train["original_class"] = "small"
train.loc[train["size_category"]==1,"original_class"] = "large"
train.original_class.value_counts()
confusion_matrix(pred_train_class,train["original_class"])
np.mean(pred_train_class==pd.Series(train["original_class"]).reset_index(drop=True)) #100%
pd.crosstab(pred_train_class,pd.Series(train["original_class"]).reset_index(drop=True))

original_class  large  small
row_0
large              10      3
small              87    261

In [71]:
pred_test = first_model.predict(np.array(x_test))
pred_test = pd.Series([i[0] for i in pred_test])
pred_test_class = pd.Series(["small"]*156)
pred_test_class[[i>0.5 for i in pred_test]] = "large"
test =pd.concat([x_test,y_test],axis=1)
test["original_class"]="small"
test.loc[test["size_category"]==1,"original_class"] = "large"

5/5 [==============================] - 0s 942us/step

In [72]:
test["original_class"].value_counts()
np.mean(pred_test_class==pd.Series(test["original_class"]).reset_index(drop=True)) # 85%
confusion_matrix(pred_test_class,test["original_class"])
pd.crosstab(pred_test_class,pd.Series(test["original_class"]).reset_index(drop=True))

original_class  large  small
row_0
large               2      4
small              40    110